-- Applied to the connected project by the product_catalog_editor migration.
-- Reference SQL for a database with the original products schema; do not re-run blindly.
alter table public.products add column description text not null default '', add column image_url text, add column is_new boolean not null default false;
alter table public.products alter column id add generated by default as identity;
do $$ declare next_id bigint; begin select coalesce(max(id),0)+1 into next_id from public.products; execute format('alter table public.products alter column id restart with %s', next_id); end $$;
grant usage, select on sequence public.products_id_seq to authenticated;
revoke truncate, references, trigger on public.products from anon, authenticated;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values ('product-images','product-images',true,5242880,array['image/jpeg','image/png','image/webp']);
create policy "LOCA admin upload product images" on storage.objects for insert to authenticated with check (bucket_id='product-images' and (select public.is_admin()));
create policy "LOCA admin read product images" on storage.objects for select to authenticated using (bucket_id='product-images' and (select public.is_admin()));
create policy "LOCA admin remove product images" on storage.objects for delete to authenticated using (bucket_id='product-images' and (select public.is_admin()));
