const SUPABASE_URL="https://qvvrjogeqranowfseivh.supabase.co";const SUPABASE_KEY="sb_publishable_IP9PzAVXsVwcqNWenmdmLg_ACtzSDMB";const supabaseClient=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let products=[],filter="All",authMode="signin",cart=JSON.parse(localStorage.getItem("loca_cart_new")||"[]");
const fallbackProducts=[{id:1,name:"Noor Cotton 3-Piece Suit",cat:"Women",price:6490,old:null,new:true},{id:2,name:"Aariz Classic Kurta",cat:"Men",price:3990,old:null,new:true},{id:3,name:"Maira Embroidered 3-Piece",cat:"Women",price:11990,old:13990,new:true},{id:4,name:"Safa Printed Lawn 2-Piece",cat:"Women",price:8290,old:null,new:false},{id:5,name:"Rayan Kameez Shalwar",cat:"Men",price:8990,old:null,new:true},{id:6,name:"Zoya Ready-to-Wear Kurti",cat:"Women",price:5490,old:null,new:false},{id:7,name:"Naveed Formal Waistcoat",cat:"Men",price:8990,old:9990,new:false},{id:8,name:"Mina Structured Handbag",cat:"Accessories",price:5990,old:null,new:true},{id:9,name:"Resham Printed Dupatta",cat:"Accessories",price:2990,old:null,new:false},{id:10,name:"Ayla Everyday Tote",cat:"Accessories",price:6990,old:null,new:false},{id:11,name:"Hadi Essential Shalwar",cat:"Men",price:3490,old:null,new:true},{id:12,name:"Iris Embroidered Khussa",cat:"Footwear",price:4490,old:null,new:true},{id:13,name:"Sultan Peshawari Chappal",cat:"Footwear",price:4990,old:null,new:false},{id:14,name:"Mina Leather Slides",cat:"Footwear",price:3990,old:null,new:false},{id:15,name:"Areeba Gold-Tone Earrings",cat:"Accessories",price:2490,old:null,new:true},{id:16,name:"Noor Signature Fragrance",cat:"Accessories",price:4990,old:null,new:false}];
const imgs=["https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=85","https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=85","https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=900&q=85","https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=85","https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=900&q=85","https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=900&q=85","https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&q=85","https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?auto=format&fit=crop&w=900&q=85"];
const money=n=>"PKR "+Number(n||0).toLocaleString("en-PK");
function normalizeProduct(p,i){return {...p,id:p.id,name:p.name,cat:p.category||p.cat||"",price:Number(p.price),old:p.old_price==null?null:Number(p.old_price),new:!!(p.is_new??p.new),image:p.image_url||p.image||imgs[i%imgs.length]}}
async function loadProducts(){const {data,error}=await supabaseClient.from("products").select("*").eq("active",true).order("id");if(error||!data?.length){products=fallbackProducts.map((p,i)=>({...p,image:imgs[i%imgs.length]}));console.warn(error)}else products=data.map(normalizeProduct);cart=cart.filter(id=>products.some(p=>String(p.id)===String(id)));localStorage.setItem("loca_cart_new",JSON.stringify(cart));initUI()}
function card(p){return `<article class="product"><div class="pic"><img loading="lazy" src="${p.image||imgs[0]}" alt="${p.name}" onerror="this.src='${imgs[0]}'">${p.new?'<span class="badge">New</span>':''}<button class="heart" onclick="event.stopPropagation();add(${p.id})">♡</button></div><div class="product-info"><span class="category">${p.cat}</span><h3>${p.name}</h3><div class="price">${money(p.price)}${p.old?`<span class="old">${money(p.old)}</span>`:""}</div><button class="add" onclick="add(${p.id})">Add to bag +</button></div></article>`}
function matchesFilter(p){const c=(p.cat||"").toLowerCase();if(filter==="All")return true;if(filter==="Women")return c.includes("women")||c.includes("woman")||c.includes("ladies");if(filter==="Men")return c.includes("men")||c.includes("man");if(filter==="Footwear")return /footwear|shoe|chappal|khussa|sandal|slide|peshawari/.test(c);if(filter==="Accessories")return /accessor|bag|jewell|jewelry|scarf|stole|wallet|belt|cap|fragrance|perfume/.test(c);return c===filter.toLowerCase()}
function render(){let list=products.filter(matchesFilter);let s=document.getElementById("sort").value;if(s==="low")list.sort((a,b)=>a.price-b.price);if(s==="high")list.sort((a,b)=>b.price-a.price);document.getElementById("grid").innerHTML=list.map(card).join("");document.getElementById("count").textContent=list.length+" products"}
function initUI(){document.getElementById("filters").innerHTML=["All","Women","Men","Footwear","Accessories"].map(x=>`<button class="filter ${x==="All"?"active":""}" onclick="setFilter('${x}',this)">${x}</button>`).join("");document.getElementById("newGrid").innerHTML=products.filter(p=>p.new).slice(0,4).map(card).join("");render();drawCart();reveal()}
function setFilter(x,b){filter=x;document.querySelectorAll(".filter").forEach(e=>e.classList.remove("active"));if(b)b.classList.add("active");render()}
function setFilterFromLink(x){setTimeout(()=>{let b=[...document.querySelectorAll('.filter')].find(e=>e.textContent===x);setFilter(x,b)},50)}
function add(id){cart.push(id);localStorage.setItem("loca_cart_new",JSON.stringify(cart));drawCart();document.getElementById("drawer").classList.add("open");document.getElementById("overlay").classList.add("open");document.body.classList.add("lock")}
function drawCart(){let box=document.getElementById("cartItems"),foot=document.getElementById("cartFoot");if(!cart.length){box.innerHTML='<div class="empty">Your bag is waiting for something good.</div>';foot.innerHTML="";return}let counts={};cart.forEach(id=>counts[id]=(counts[id]||0)+1);box.innerHTML=Object.entries(counts).map(([id,q])=>{let p=products.find(x=>String(x.id)===String(id));return p?`<div class="cart-item"><div class="mini"><img src="${p.image||imgs[0]}" alt=""></div><div><strong>${p.name}</strong><p style="color:var(--muted);font-size:11px">${money(p.price)} · Qty ${q}</p><button onclick="removeItem(${id})" style="border:0;background:none;padding:0;color:var(--accent);font-size:10px;text-transform:uppercase;letter-spacing:.1em">Remove</button></div></div>`:""}).join("");let total=cart.reduce((s,id)=>s+(products.find(p=>String(p.id)===String(id))?.price||0),0);foot.innerHTML=`<div style="display:flex;justify-content:space-between;margin-bottom:16px;font-size:12px"><span>Subtotal</span><strong>${money(total)}</strong></div><button class="btn" style="width:100%" onclick="openCheckout()">Checkout ↗</button>`}
async function openCheckout(){if(!cart.length){alert("Your bag is empty.");return}const {data:{session}}=await supabaseClient.auth.getSession();if(!session?.user){authMode="signin";updateAuthUI();openAuth();alert("Please sign in or create a LOCA account before checkout.");return}let total=cart.reduce((s,id)=>s+(products.find(p=>String(p.id)===String(id))?.price||0),0);document.getElementById("coTotal").textContent=money(total);document.getElementById("coEmail").value=session.user.email||"";document.getElementById("checkoutModal").classList.add("open");document.body.classList.add("lock")}
function closeCheckout(){document.getElementById("checkoutModal").classList.remove("open");document.body.classList.remove("lock")}
async function placeOrder(e){e.preventDefault();const orderForm=e.currentTarget?.closest?.("form")||e.target?.closest?.("form")||document.getElementById("checkoutForm");if(!cart.length)return;const {data:{user}}=await supabaseClient.auth.getUser();if(!user){closeCheckout();authMode="signin";updateAuthUI();openAuth();alert("Sign in is required before placing an order.");return}const btn=orderForm?.querySelector("button:last-child");if(btn){btn.disabled=true;btn.textContent="Placing order..."}try{const counts={};cart.forEach(id=>counts[id]=(counts[id]||0)+1);const items=Object.entries(counts).map(([id,quantity])=>({product_id:Number(id),quantity:Number(quantity)}));const {data,error}=await supabaseClient.rpc("place_order",{p_name:document.getElementById("coName").value.trim(),p_phone:document.getElementById("coPhone").value.trim(),p_email:document.getElementById("coEmail").value.trim(),p_address:document.getElementById("coAddress").value.trim(),p_city:document.getElementById("coCity").value.trim(),p_payment:document.getElementById("coPayment").value,p_items:items});if(error)throw error;const result=Array.isArray(data)?data[0]:data;const orderNo=result?.order_number||result?.order_no||result?.id||"LOCA-ORDER";cart=[];localStorage.setItem("loca_cart_new","[]");drawCart();closeCheckout();toggleCart();alert("Order placed successfully. Order ID: "+orderNo+"\n\nThank you for shopping with LOCA COLLECTION.");if(orderForm&&typeof orderForm.reset==='function')orderForm.reset()}catch(err){console.error(err);alert("Order could not be placed. Please try again.\n\n"+(err.message||"Connection error"))}finally{if(btn){btn.disabled=false;btn.textContent="Place Order ↗"}}}
function removeItem(id){let i=cart.indexOf(id);if(i>-1)cart.splice(i,1);localStorage.setItem("loca_cart_new",JSON.stringify(cart));drawCart()}
function toggleCart(){let d=document.getElementById("drawer"),o=document.getElementById("overlay");d.classList.toggle("open");o.classList.toggle("open");document.body.classList.toggle("lock",d.classList.contains("open"))}
function toggleMenu(){let n=document.querySelector(".navlinks");n.style.display=n.style.display==="flex"?"none":"flex";n.style.position="absolute";n.style.top="68px";n.style.left="0";n.style.right="0";n.style.background="var(--paper)";n.style.padding="20px 25px";n.style.flexDirection="column";n.style.borderBottom="1px solid var(--line)"}
function searchProducts(){let q=prompt("Search LOCA products");if(!q)return;let p=products.filter(x=>x.name.toLowerCase().includes(q.toLowerCase())||x.cat.toLowerCase().includes(q.toLowerCase()));if(p.length){document.getElementById("shop").scrollIntoView({behavior:"smooth"});alert(p.map(x=>x.name+" — "+money(x.price)).join("\n"))}else alert("No products found.")}
function updateAuthUI(){document.getElementById("authTitle").textContent=authMode==="signin"?"Sign in to continue.":"Create your LOCA account.";document.getElementById("authSubmit").textContent=authMode==="signin"?"Sign In":"Create Account";document.getElementById("authSwitch").innerHTML=authMode==="signin"?'New to LOCA? <button onclick="toggleAuthMode();return false">Create an account</button>':'Already have an account? <button onclick="toggleAuthMode();return false">Sign in</button>'}
function openAuth(){updateAuthUI();document.getElementById("authModal").classList.add("open");document.body.classList.add("lock")}
function closeAuth(){document.getElementById("authModal").classList.remove("open");document.body.classList.remove("lock")}
function toggleAuthMode(){authMode=authMode==="signin"?"signup":"signin";updateAuthUI()}
async function handleAuth(e){e.preventDefault();let email=document.getElementById("authEmail").value.trim(),password=document.getElementById("authPassword").value,btn=document.getElementById("authSubmit");btn.disabled=true;btn.textContent=authMode==="signin"?"Signing in...":"Creating account...";try{let result=authMode==="signin"?await supabaseClient.auth.signInWithPassword({email,password}):await supabaseClient.auth.signUp({email,password});if(result.error)throw result.error;if(authMode==="signup"&&!result.data.session){alert("Account created. Please verify your email, then sign in before checkout.");authMode="signin";updateAuthUI();return}closeAuth();if(cart.length)openCheckout()}catch(err){alert(err.message||"Authentication failed.")}finally{btn.disabled=false;updateAuthUI()}}
async function signOutCustomer(){await supabaseClient.auth.signOut();alert("You have been signed out.")}
function subscribe(e){e.preventDefault();document.getElementById("msg").textContent="Thank you — you're on the LOCA list.";document.getElementById("msg").style.marginTop="16px"}
function reveal(){document.querySelectorAll(".reveal").forEach(el=>{if(el.dataset.revealed)return;let ob=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){x.target.classList.add("visible");x.target.dataset.revealed="1";ob.disconnect()}}),{threshold:.12});ob.observe(el)})}
window.addEventListener("mousemove",e=>{let d=document.getElementById("cursorDot");d.style.left=e.clientX+"px";d.style.top=e.clientY+"px"});
supabaseClient.auth.onAuthStateChange((_event,session)=>{if(session?.user){document.querySelectorAll(".user-dot").forEach(x=>x.textContent="●")}else document.querySelectorAll(".user-dot").forEach(x=>x.textContent="♙")});
updateAuthUI();
loadProducts();