window.LOCA=window.LOCA||{};
const LOCA_PUBLIC_SITE_URL='https://locacollection.github.io/locacollection1/';

function updateAuthUI(){const signup=LOCA.authMode==='signup',title=document.getElementById('authTitle'),intro=document.getElementById('authIntro'),submit=document.getElementById('authSubmit'),name=document.getElementById('authNameField'),confirm=document.getElementById('authConfirmField'),switcher=document.getElementById('authSwitch');if(!title)return;title.textContent=signup?'Create your LOCA account.':'Welcome back.';intro.textContent=signup?'Create one account for saved bag, profile and order history.':'Sign in to save your bag and keep your orders together.';submit.textContent=signup?'Create account ↗':'Sign in ↗';name.hidden=!signup;confirm.hidden=!signup;switcher.innerHTML=signup?'Already have an account? <button type="button" onclick="toggleAuthMode()">Sign in</button>':'New to LOCA? <button type="button" onclick="toggleAuthMode()">Create an account</button>'}
function openAuth(mode='signin'){LOCA.authMode=mode;updateAuthUI();document.getElementById('authModal')?.classList.add('open');document.body.classList.add('lock');setTimeout(()=>document.getElementById('authEmail')?.focus(),80)}
function closeAuth(){document.getElementById('authModal')?.classList.remove('open');if(!document.querySelector('.modal-layer.open,.checkout-modal.open,.bag-drawer.open,.site-notice-layer.open'))document.body.classList.remove('lock')}
function toggleAuthMode(){LOCA.authMode=LOCA.authMode==='signin'?'signup':'signin';updateAuthUI()}
async function handleAuth(event){event.preventDefault();const email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value,name=document.getElementById('authName').value.trim(),confirm=document.getElementById('authConfirm').value,button=document.getElementById('authSubmit');if(LOCA.authMode==='signup'&&(!name||password!==confirm)){LOCA.notice({eyebrow:'Account details',title:!name?'Enter your full name.':'Passwords do not match.',message:!name?'Your name helps us keep delivery and order details clear.':'Re-enter the same password in both fields.',tone:'error',action:'Review details'});return}button.disabled=true;button.textContent=LOCA.authMode==='signup'?'Creating account...':'Signing in...';try{const result=LOCA.authMode==='signup'?await LOCA.db.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:LOCA_PUBLIC_SITE_URL}}):await LOCA.db.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(LOCA.authMode==='signup'&&!result.data.session){LOCA.notice({eyebrow:'Account created',title:'Check your email.',message:'Use the confirmation link we sent, then return to sign in to your LOCA account.',tone:'success',action:'Continue'});LOCA.authMode='signin';updateAuthUI();return}closeAuth()}catch(error){LOCA.notice({eyebrow:'Account access',title:'We could not complete that request.',message:error.message||'Authentication failed. Please try again.',tone:'error',action:'Try again'})}finally{button.disabled=false;updateAuthUI()}}

LOCA.ensureProfile=async function(){if(!LOCA.currentUser)return null;const{data,error}=await LOCA.db.from('profiles').select('*').eq('id',LOCA.currentUser.id).maybeSingle();if(error)throw error;if(data){LOCA.profile=data;return data}const email=LOCA.currentUser.email||'',fallback={id:LOCA.currentUser.id,email,contact_email:email,full_name:LOCA.currentUser.user_metadata?.full_name||''};const{data:inserted,error:insertError}=await LOCA.db.from('profiles').insert(fallback).select('*').single();if(insertError)throw insertError;LOCA.profile=inserted;return inserted};
function renderAccountHeader(){document.querySelectorAll('.account-button').forEach(button=>{button.title=LOCA.currentUser?'My Account':'Sign in / Create account';button.classList.toggle('is-signed-in',!!LOCA.currentUser)})}
function initials(value){return String(value||'LOCA').trim().split(/\s+/).slice(0,2).map(part=>part[0]||'').join('').toUpperCase()||'L'}
function showInlineMessage(id,text){const box=document.getElementById(id);if(!box)return;box.textContent=text;box.hidden=false;setTimeout(()=>box.hidden=true,2600)}
function populateProfileForm(){const profile=LOCA.profile||{},registered=LOCA.currentUser?.email||profile.email||'',name=profile.full_name||registered.split('@')[0]||'LOCA member',contact=profile.contact_email||registered;document.getElementById('profileEmail').value=registered;document.getElementById('profileName').value=profile.full_name||'';document.getElementById('contactRegisteredEmail').value=registered;document.getElementById('contactEmail').value=contact;document.getElementById('contactPhone').value=profile.phone||'';document.getElementById('accountIdentity').textContent=name+' · '+registered;document.getElementById('accountMemberName').textContent=name;document.getElementById('accountMemberEmail').textContent=registered;document.getElementById('accountAvatar').textContent=initials(name)}
function switchAccountSection(name='profile'){const valid=['profile','orders','addresses','contact'];if(!valid.includes(name))name='profile';document.querySelectorAll('[data-account-section]').forEach(button=>button.classList.toggle('active',button.dataset.accountSection===name));document.querySelectorAll('[data-account-panel]').forEach(panel=>{const active=panel.dataset.accountPanel===name;panel.hidden=!active;panel.classList.toggle('active',active)});if(name==='orders')loadMyOrders();if(name==='addresses'&&window.loadDeliveryAddresses)loadDeliveryAddresses({seed:true})}
async function openAccount(section='profile'){if(!LOCA.currentUser){openAuth('signin');return}try{await LOCA.ensureProfile();populateProfileForm();document.getElementById('accountModal')?.classList.add('open');document.body.classList.add('lock');switchAccountSection(section);Promise.allSettled([loadMyOrders(),window.loadDeliveryAddresses?loadDeliveryAddresses({seed:true}):Promise.resolve()])}catch(error){LOCA.notice({eyebrow:'My account',title:'Your profile could not be loaded.',message:error.message||'Please try again in a moment.',tone:'error',action:'Close'})}}
function closeAccount(){document.getElementById('accountModal')?.classList.remove('open');if(!document.querySelector('.modal-layer.open,.checkout-modal.open,.bag-drawer.open,.site-notice-layer.open'))document.body.classList.remove('lock')}
async function saveProfile(event){event.preventDefault();const button=document.getElementById('profileSave');button.disabled=true;button.textContent='Saving…';try{const payload={id:LOCA.currentUser.id,email:LOCA.currentUser.email||'',contact_email:LOCA.profile?.contact_email||LOCA.currentUser.email||'',full_name:document.getElementById('profileName').value.trim(),updated_at:new Date().toISOString()};const{data,error}=await LOCA.db.from('profiles').upsert(payload).select('*').single();if(error)throw error;LOCA.profile=data;populateProfileForm();showInlineMessage('accountMessage','Profile saved successfully.')}catch(error){LOCA.notice({eyebrow:'My profile',title:'Your profile was not saved.',message:error.message||'Please review your details and try again.',tone:'error',action:'Review profile'})}finally{button.disabled=false;button.textContent='Save profile'}}
async function saveContactInfo(event){event.preventDefault();const button=document.getElementById('contactSave'),phone=document.getElementById('contactPhone').value.trim(),contact_email=document.getElementById('contactEmail').value.trim();if(!phone||!contact_email){LOCA.notice({eyebrow:'Contact info',title:'Complete your contact details.',message:'Add a valid delivery email and phone or WhatsApp number.',tone:'error',action:'Review details'});return}button.disabled=true;button.textContent='Saving…';try{const{data,error}=await LOCA.db.from('profiles').update({phone,contact_email,updated_at:new Date().toISOString()}).eq('id',LOCA.currentUser.id).select('*').single();if(error)throw error;LOCA.profile=data;populateProfileForm();showInlineMessage('contactMessage','Contact information saved.')}catch(error){LOCA.notice({eyebrow:'Contact info',title:'Contact details were not saved.',message:error.message||'Please try again.',tone:'error',action:'Review details'})}finally{button.disabled=false;button.textContent='Save contact info'}}
async function signOutCustomer(){await LOCA.db.auth.signOut();closeAccount()}
async function handleSession(session){LOCA.currentUser=session?.user||null;LOCA.profile=null;LOCA.addresses=[];renderAccountHeader();if(LOCA.currentUser){try{await LOCA.ensureProfile();await LOCA.loadCart({mergeGuest:true})}catch(error){console.warn('Account setup failed',error);await LOCA.loadCart()}}else{await LOCA.loadCart()}}
async function initAuth(){LOCA.authMode='signin';updateAuthUI();document.querySelectorAll('[data-account-section]').forEach(button=>button.addEventListener('click',()=>switchAccountSection(button.dataset.accountSection)));const{data:{session}}=await LOCA.db.auth.getSession();await handleSession(session);LOCA.db.auth.onAuthStateChange((_event,newSession)=>setTimeout(()=>handleSession(newSession),0))}
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&document.getElementById('accountModal')?.classList.contains('open'))closeAccount()});
window.openAuth=openAuth;window.closeAuth=closeAuth;window.toggleAuthMode=toggleAuthMode;window.handleAuth=handleAuth;window.openAccount=openAccount;window.closeAccount=closeAccount;window.switchAccountSection=switchAccountSection;window.saveProfile=saveProfile;window.saveContactInfo=saveContactInfo;window.signOutCustomer=signOutCustomer;window.initAuth=initAuth;