window.LOCA=window.LOCA||{};
const LOCA_PUBLIC_SITE_URL='https://locacollection.github.io/locacollection1/';
function updateAuthUI(){const signup=LOCA.authMode==='signup';const title=document.getElementById('authTitle'),intro=document.getElementById('authIntro'),submit=document.getElementById('authSubmit'),name=document.getElementById('authNameField'),confirm=document.getElementById('authConfirmField'),switcher=document.getElementById('authSwitch');if(!title)return;title.textContent=signup?'Create your LOCA account.':'Welcome back.';intro.textContent=signup?'Create one account for saved bag, profile and order history.':'Sign in to save your bag and keep your orders together.';submit.textContent=signup?'Create account ↗':'Sign in ↗';name.hidden=!signup;confirm.hidden=!signup;switcher.innerHTML=signup?'Already have an account? <button type="button" onclick="toggleAuthMode()">Sign in</button>':'New to LOCA? <button type="button" onclick="toggleAuthMode()">Create an account</button>'}
function openAuth(mode='signin'){LOCA.authMode=mode;updateAuthUI();document.getElementById('authModal')?.classList.add('open');document.body.classList.add('lock');setTimeout(()=>document.getElementById('authEmail')?.focus(),80)}
function closeAuth(){document.getElementById('authModal')?.classList.remove('open');if(!document.querySelector('.modal-layer.open,.checkout-modal.open,.bag-drawer.open'))document.body.classList.remove('lock')}
function toggleAuthMode(){LOCA.authMode=LOCA.authMode==='signin'?'signup':'signin';updateAuthUI()}
async function handleAuth(e){e.preventDefault();const email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value,name=document.getElementById('authName').value.trim(),confirm=document.getElementById('authConfirm').value,button=document.getElementById('authSubmit');if(LOCA.authMode==='signup'&&(!name||password!==confirm)){LOCA.notice({eyebrow:'Account details',title:!name?'Enter your full name.':'Passwords do not match.',message:!name?'Your name helps us keep delivery and order details clear.':'Re-enter the same password in both fields.',tone:'error',action:'Review details'});return}button.disabled=true;button.textContent=LOCA.authMode==='signup'?'Creating account...':'Signing in...';try{const result=LOCA.authMode==='signup'?await LOCA.db.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:LOCA_PUBLIC_SITE_URL}}):await LOCA.db.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(LOCA.authMode==='signup'&&!result.data.session){LOCA.notice({eyebrow:'Account created',title:'Check your email.',message:'Use the confirmation link we sent, then return to sign in to your LOCA account.',tone:'success',action:'Continue'});LOCA.authMode='signin';updateAuthUI();return}closeAuth()}catch(err){LOCA.notice({eyebrow:'Account access',title:'We could not complete that request.',message:err.message||'Authentication failed. Please try again.',tone:'error',action:'Try again'})}finally{button.disabled=false;updateAuthUI()}}
LOCA.ensureProfile=async function(){if(!LOCA.currentUser)return null;const{data,error}=await LOCA.db.from('profiles').select('*').eq('id',LOCA.currentUser.id).maybeSingle();if(error)throw error;if(data){LOCA.profile=data;return data}const fallback={id:LOCA.currentUser.id,email:LOCA.currentUser.email||'',full_name:LOCA.currentUser.user_metadata?.full_name||''};const{data:inserted,error:insertError}=await LOCA.db.from('profiles').insert(fallback).select('*').single();if(insertError)throw insertError;LOCA.profile=inserted;return inserted};
function renderAccountHeader(){document.querySelectorAll('.account-button').forEach(b=>{b.title=LOCA.currentUser?'My Account':'Sign in / Create account';b.classList.toggle('is-signed-in',!!LOCA.currentUser)});}
async function openAccount(){if(!LOCA.currentUser){openAuth('signin');return}try{await LOCA.ensureProfile();populateProfileForm();document.getElementById('accountModal')?.classList.add('open');document.body.classList.add('lock');loadMyOrders()}catch(err){LOCA.notice({eyebrow:'My account',title:'Your profile could not be loaded.',message:err.message||'Please try again in a moment.',tone:'error',action:'Close'})}}
function closeAccount(){document.getElementById('accountModal')?.classList.remove('open');if(!document.querySelector('.modal-layer.open,.checkout-modal.open,.bag-drawer.open'))document.body.classList.remove('lock')}
function populateProfileForm(){const p=LOCA.profile||{},email=LOCA.currentUser?.email||p.email||'';document.getElementById('profileEmail').value=email;document.getElementById('profileName').value=p.full_name||'';document.getElementById('profilePhone').value=p.phone||'';document.getElementById('profileCity').value=p.city||'';document.getElementById('profileAddress').value=p.address||'';document.getElementById('accountIdentity').textContent=(p.full_name||email)+' · '+email}
async function saveProfile(e){e.preventDefault();const b=document.getElementById('profileSave');b.disabled=true;b.textContent='Saving...';try{const payload={id:LOCA.currentUser.id,email:LOCA.currentUser.email||'',full_name:document.getElementById('profileName').value.trim(),phone:document.getElementById('profilePhone').value.trim(),city:document.getElementById('profileCity').value.trim(),address:document.getElementById('profileAddress').value.trim(),updated_at:new Date().toISOString()};const{data,error}=await LOCA.db.from('profiles').upsert(payload).select('*').single();if(error)throw error;LOCA.profile=data;populateProfileForm();const m=document.getElementById('accountMessage');m.textContent='Profile saved.';m.hidden=false;setTimeout(()=>m.hidden=true,2200)}catch(err){LOCA.notice({eyebrow:'My account',title:'Your profile was not saved.',message:err.message||'Please review your details and try again.',tone:'error',action:'Review profile'})}finally{b.disabled=false;b.textContent='Save profile'}}
async function signOutCustomer(){await LOCA.db.auth.signOut();closeAccount()}
async function handleSession(session){LOCA.currentUser=session?.user||null;LOCA.profile=null;renderAccountHeader();if(LOCA.currentUser){try{await LOCA.ensureProfile();await LOCA.loadCart({mergeGuest:true})}catch(err){console.warn('Account setup failed',err);await LOCA.loadCart()}}else{await LOCA.loadCart()}}
async function initAuth(){LOCA.authMode='signin';updateAuthUI();const{data:{session}}=await LOCA.db.auth.getSession();await handleSession(session);LOCA.db.auth.onAuthStateChange((_event,newSession)=>setTimeout(()=>handleSession(newSession),0))}
window.openAuth=openAuth;window.closeAuth=closeAuth;window.toggleAuthMode=toggleAuthMode;window.handleAuth=handleAuth;window.openAccount=openAccount;window.closeAccount=closeAccount;window.saveProfile=saveProfile;window.signOutCustomer=signOutCustomer;window.initAuth=initAuth;