window.LOCA=window.LOCA||{};
LOCA.GUEST_CART_KEY='loca_guest_cart_v3';
LOCA.readGuestCart=function(){try{const raw=localStorage.getItem(LOCA.GUEST_CART_KEY)||'{}',parsed=JSON.parse(raw);const out={};Object.entries(parsed||{}).forEach(([id,q])=>{const n=Math.min(20,Math.max(0,Number(q)||0));if(n)out[String(id)]=n});return out}catch{return{}}};
LOCA.writeGuestCart=function(cart){localStorage.setItem(LOCA.GUEST_CART_KEY,JSON.stringify(cart||{}))};
LOCA.cartTotalQuantity=function(){return Object.values(LOCA.cart||{}).reduce((s,q)=>s+Number(q||0),0)};
async function add(id){const key=String(id);LOCA.cart[key]=Math.min(20,Number(LOCA.cart[key]||0)+1);LOCA.writeGuestCart(LOCA.cart);drawCart();openCartDrawer()}
async function removeItem(id){delete LOCA.cart[String(id)];LOCA.writeGuestCart(LOCA.cart);drawCart()}
async function changeCartQty(id,delta){const key=String(id),next=Math.min(20,Math.max(0,Number(LOCA.cart[key]||0)+Number(delta||0)));if(next)LOCA.cart[key]=next;else delete LOCA.cart[key];LOCA.writeGuestCart(LOCA.cart);drawCart()}
async function clearCart(){LOCA.cart={};LOCA.writeGuestCart({});drawCart()}
function drawCart(){const box=document.getElementById('cartItems'),foot=document.getElementById('cartFoot');if(!box||!foot)return;const entries=Object.entries(LOCA.cart||{}).filter(([,q])=>Number(q)>0);if(!entries.length){box.innerHTML='<div class="empty">Your bag is waiting for something good.</div>';foot.innerHTML='';updateCartBadge();return}box.innerHTML=entries.map(([id,q])=>{const p=LOCA.products.find(x=>String(x.id)===String(id));if(!p)return'';return`<div class="cart-item"><div class="mini"><img src="${LOCA.escape(LOCA.safeImage(p.image))}" alt=""></div><div class="cart-item-copy"><strong>${LOCA.escape(p.name)}</strong><p>${LOCA.money(p.price)}</p><div class="qty-row"><button type="button" onclick="changeCartQty(${id},-1)" aria-label="Decrease quantity">−</button><span>${q}</span><button type="button" onclick="changeCartQty(${id},1)" aria-label="Increase quantity">＋</button><button type="button" class="remove-link" onclick="removeItem(${id})">Remove</button></div></div></div>`}).join('');const total=entries.reduce((s,[id,q])=>{const p=LOCA.products.find(x=>String(x.id)===String(id));return s+(p?p.price*Number(q):0)},0);foot.innerHTML=`<div class="cart-summary"><span>Subtotal</span><strong>${LOCA.money(total)}</strong></div><button class="button primary" style="width:100%" onclick="openCheckout()">Checkout <span>↗</span></button>`;updateCartBadge()}
function updateCartBadge(){const b=document.getElementById('cartCount');if(!b)return;const q=LOCA.cartTotalQuantity();b.textContent=q>99?'99+':String(q);b.hidden=!q}
function openCartDrawer(){document.getElementById('drawer')?.classList.add('open');document.getElementById('overlay')?.classList.add('open');document.body.classList.add('lock')}
function toggleCart(){const d=document.getElementById('drawer'),o=document.getElementById('overlay');if(!d||!o)return;d.classList.toggle('open');o.classList.toggle('open');document.body.classList.toggle('lock',d.classList.contains('open'))}
window.add=add;window.removeItem=removeItem;window.changeCartQty=changeCartQty;window.clearCart=clearCart;window.drawCart=drawCart;window.toggleCart=toggleCart;window.openCartDrawer=openCartDrawer;