window.LOCA=window.LOCA||{};LOCA.GUEST_CART_KEY='loca_guest_cart_v4';LOCA.readGuestCart=()=>{try{return JSON.parse(localStorage.getItem(LOCA.GUEST_CART_KEY)||'{}')}catch{return{}}};LOCA.writeGuestCart=cart=>localStorage.setItem(LOCA.GUEST_CART_KEY,JSON.stringify(cart||{}));LOCA.cartTotalQuantity=()=>Object.values(LOCA.cart||{}).reduce((s,q)=>s+Number(q||0),0);
LOCA.loadServerCart=async uid=>{const{data,error}=await LOCA.db.from('cart_items').select('product_id,quantity').eq('user_id',uid);if(error)throw error;return Object.fromEntries((data||[]).map(r=>[String(r.product_id),Number(r.quantity)]))};
LOCA.mergeGuestCartIntoAccount=async uid=>{const guest=LOCA.readGuestCart();if(!Object.keys(guest).length)return;const server=await LOCA.loadServerCart(uid);const rows=Object.entries(guest).map(([product_id,quantity])=>({user_id:uid,product_id:Number(product_id),quantity:Math.min(20,Number(quantity)+Number(server[product_id]||0)),updated_at:new Date().toISOString()}));if(rows.length){const{error}=await LOCA.db.from('cart_items').upsert(rows,{onConflict:'user_id,product_id'});if(error)throw error}LOCA.writeGuestCart({})};
LOCA.loadCart=async({mergeGuest=false}={})=>{try{if(LOCA.currentUser){if(mergeGuest)await LOCA.mergeGuestCartIntoAccount(LOCA.currentUser.id);LOCA.cart=await LOCA.loadServerCart(LOCA.currentUser.id)}else LOCA.cart=LOCA.readGuestCart();drawCart()}catch(err){console.warn('Cart sync failed',err);LOCA.cart=LOCA.readGuestCart();drawCart()}};
LOCA.persistCartItem=async(id,q)=>{if(!LOCA.currentUser){LOCA.writeGuestCart(LOCA.cart);return}if(q<=0){const{error}=await LOCA.db.from('cart_items').delete().eq('user_id',LOCA.currentUser.id).eq('product_id',Number(id));if(error)throw error}else{const{error}=await LOCA.db.from('cart_items').upsert({user_id:LOCA.currentUser.id,product_id:Number(id),quantity:Math.min(20,q),updated_at:new Date().toISOString()},{onConflict:'user_id,product_id'});if(error)throw error}};
async function addQuantity(id,quantity=1,{open=true}={}){const k=String(id),amount=Math.max(1,Math.min(20,Number(quantity)||1));LOCA.cart[k]=Math.min(20,Number(LOCA.cart[k]||0)+amount);drawCart();await LOCA.persistCartItem(id,LOCA.cart[k]);if(open)openCartDrawer()}async function add(id){return addQuantity(id,1)}async function removeItem(id){delete LOCA.cart[String(id)];drawCart();await LOCA.persistCartItem(id,0)}async function changeCartQty(id,d){const k=String(id),q=Math.max(0,Math.min(20,Number(LOCA.cart[k]||0)+d));if(q)LOCA.cart[k]=q;else delete LOCA.cart[k];drawCart();await LOCA.persistCartItem(id,q)}async function clearCart(){if(LOCA.currentUser)await LOCA.db.from('cart_items').delete().eq('user_id',LOCA.currentUser.id);LOCA.cart={};LOCA.writeGuestCart({});drawCart()}
function drawCart(){const box=document.getElementById('cartItems'),foot=document.getElementById('cartFoot');if(!box||!foot)return;const entries=Object.entries(LOCA.cart||{}).filter(([,q])=>Number(q)>0);if(!entries.length){box.innerHTML='<div class="empty">Your bag is waiting for something good.</div>';foot.innerHTML='';updateCartBadge();return}box.innerHTML=entries.map(([id,q])=>{const p=LOCA.products.find(x=>String(x.id)===String(id));if(!p)return'';return`<div class="cart-item"><div class="mini"><img src="${LOCA.escape(LOCA.safeImage(p.image))}" alt=""></div><div class="cart-item-copy"><strong>${LOCA.escape(p.name)}</strong><p>${LOCA.money(p.price)}</p><div class="qty-row"><button type="button" onclick="changeCartQty(${id},-1)">−</button><span>${q}</span><button type="button" onclick="changeCartQty(${id},1)">＋</button><button type="button" class="remove-link" onclick="removeItem(${id})">Remove</button></div></div></div>`}).join('');const total=entries.reduce((s,[id,q])=>{const p=LOCA.products.find(x=>String(x.id)===String(id));return s+(p?p.price*q:0)},0);foot.innerHTML=`<div class="cart-summary"><span>Subtotal</span><strong>${LOCA.money(total)}</strong></div><button class="button primary" style="width:100%" onclick="openCheckout()">Checkout <span>↗</span></button>`;updateCartBadge()}
function updateCartBadge(){const b=document.getElementById('cartCount'),q=LOCA.cartTotalQuantity();if(b){b.textContent=q>99?'99+':q;b.hidden=!q}}
function openCartDrawer(){document.getElementById('drawer')?.classList.add('open');document.getElementById('overlay')?.classList.add('open');document.body.classList.add('lock')}function toggleCart(){const d=document.getElementById('drawer'),o=document.getElementById('overlay');d?.classList.toggle('open');o?.classList.toggle('open');document.body.classList.toggle('lock',d?.classList.contains('open'))}
const originalAddQuantity=addQuantity;
addQuantity=async function(id,quantity=1,options={}){if(LOCA.profile?.role==='admin'){LOCA.notice?.({eyebrow:'Catalogue Preview Mode',title:'Admins cannot place orders.',message:'The storefront is read-only for Admin Studio catalogue review.',action:'Continue browsing'});return false}return originalAddQuantity(id,quantity,options)};
window.add=add;window.addQuantity=addQuantity;window.removeItem=removeItem;window.changeCartQty=changeCartQty;window.clearCart=clearCart;window.drawCart=drawCart;window.toggleCart=toggleCart;window.openCartDrawer=openCartDrawer;
