window.LOCA=window.LOCA||{};
LOCA.filter='All';
LOCA.money=n=>'PKR '+Number(n||0).toLocaleString('en-PK');
LOCA.normalizeProduct=function(p){const catalogItem=(LOCA.CATALOG_PRODUCTS||[]).find(c=>Number(c.id)===Number(p.id));const rejected=!p.image_url||p.image_url.includes('unsplash.com')||p.image_url.includes('placeholder')||p.image_url.includes('photo-');const name=p.name||catalogItem?.name||'';const cat=p.category||p.cat||catalogItem?.category||'';const desc=p.description||catalogItem?.description||'';const img=catalogItem?.image_url&&rejected?catalogItem.image_url:(p.image_url||catalogItem?.image_url||p.image||'');return{...p,id:p.id,name,cat,category:cat,price:Number(p.price||catalogItem?.price||0),old:p.old_price!=null?Number(p.old_price):(catalogItem?.old_price??null),new:!!(p.is_new??p.new??catalogItem?.is_new),description:desc,image:img}};
LOCA.esc=LOCA.escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
LOCA.safeImage=value=>{if(!value||typeof value!=='string')return'assets/product-placeholder.svg';const t=value.trim();if(t.startsWith('assets/')||t.startsWith('/assets/')||t.startsWith('src/assets/'))return t;try{const u=new URL(t);if(u.protocol==='https:')return u.href}catch{}return'assets/product-placeholder.svg'};
LOCA.productCard=function(p){const e=LOCA.escape,id=Number(p.id),discount=p.old&&p.old>p.price?Math.round((p.old-p.price)/p.old*100):0;return`<article class="product"><div class="pic"><img loading="lazy" src="${e(LOCA.safeImage(p.image))}" alt="${e(p.name)}" onerror="this.onerror=null;this.src='assets/product-placeholder.svg'"><div class="product-badges">${p.new?'<span class="badge new-badge">New Arrival</span>':''}${discount>0?`<span class="badge sale-badge">SAVE ${discount}%</span>`:''}</div><button class="heart" aria-label="Add ${e(p.name)} to bag" onclick="add(${id})">＋</button></div><div class="product-info"><div class="category-row"><span class="category">${e(p.cat)}</span><span class="delivery-pill">COD in PK</span></div><h3>${e(p.name)}</h3><div class="price">${LOCA.money(p.price)}${p.old?`<span class="old">${LOCA.money(p.old)}</span>`:''}</div>${p.description?`<details class="product-description"><summary>Fabric &amp; details</summary><p>${e(p.description)}</p></details>`:''}<button class="add" onclick="add(${id})"><span aria-hidden="true">＋</span> Add to bag</button></div></article>`};
LOCA.matchesFilter=function(p){const c=(p.cat||'').toLowerCase(),f=LOCA.filter;if(f==='All')return true;if(c===f.toLowerCase())return true;if(f.includes(' - ')){const sub=f.split(' - ')[1].trim().toLowerCase();return c.includes(sub)||p.name.toLowerCase().includes(sub)}if(f==='Women')return!(c.includes('men')&&!c.includes('women'))&&(c.includes('women')||c.includes('woman')||c.includes('ladies'));if(f==='Men')return!(c.includes('women')||c.includes('woman')||c.includes('ladies'))&&/\b(men|man|mens|male)\b/.test(c);if(f==='Footwear')return/footwear|shoe|chappal|khussa|sandal|slide|peshawari|loafer|heel/.test(c);if(f==='Accessories')return/accessor|bag|jewell|jewelry|scarf|stole|wallet|belt|cap|clutch|watch/.test(c);if(f==='Fragrance')return/fragrance|perfume|attar|oudh|mist|scent/.test(c);if(f==='Kids')return/kid|teen|boy|girl|child/.test(c);return c.includes(f.toLowerCase())};
function uniqueProducts(list){const seen=new Set();return(list||[]).filter(p=>{const key=[String(p.name||'').trim().toLowerCase(),String(p.category||p.cat||'').trim().toLowerCase(),Number(p.price||0),String(p.image_url||p.image||'').trim().toLowerCase()].join('|');if(seen.has(key))return false;seen.add(key);return true})}
async function loadProducts(){const deletedIds=new Set((()=>{try{return JSON.parse(localStorage.getItem('loca_deleted_product_ids')||'[]').map(String)}catch{return[]}})());try{const{data,error}=await LOCA.db.from('products').select('*').eq('active',true).order('id');if(error)throw error;LOCA.products=uniqueProducts((data||[]).filter(p=>!deletedIds.has(String(p.id))).map(LOCA.normalizeProduct));initStoreUI()}catch(error){LOCA.products=[];initStoreUI();console.warn('Product load failed:',error.message)}if(window.drawCart)drawCart()}
function render(){const query=(document.getElementById('productSearch')?.value||'').trim().toLowerCase();let list=(LOCA.products||[]).filter(LOCA.matchesFilter).filter(p=>!query||`${p.name} ${p.cat} ${p.description||''}`.toLowerCase().includes(query));const sort=document.getElementById('sort')?.value||'featured';if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);const grid=document.getElementById('grid'),count=document.getElementById('count');if(grid)grid.innerHTML=list.length?list.map(LOCA.productCard).join(''):'<div class="search-empty"><h3>No matches just yet.</h3><p>Try another search or choose a different category.</p></div>';if(count)count.textContent=list.length+' products'}
function initStoreUI(){const filters=document.getElementById('filters');if(filters){const taxonomy=window.LOCA.CATEGORY_TAXONOMY||[{id:'All',label:'All',subcategories:[]},{id:'Women',label:'Women',subcategories:[]},{id:'Men',label:'Men',subcategories:[]},{id:'Footwear',label:'Footwear',subcategories:[]},{id:'Accessories',label:'Accessories',subcategories:[]}];let activeMain='All';if(LOCA.filter!=='All')activeMain=LOCA.filter.includes(' - ')?LOCA.filter.split(' - ')[0].trim():LOCA.filter;const current=taxonomy.find(t=>t.id===activeMain),has=current&&current.subcategories?.length;let html='<div class="main-filters">'+taxonomy.map(x=>`<button type="button" class="filter ${x.id===activeMain?'active':''}" data-category="${LOCA.escape(x.id)}" onclick="setFilter(this.dataset.category,this)">${LOCA.escape(x.label||x.id)}</button>`).join('')+'</div>';if(has){html+='<div class="sub-filters"><span class="sub-filter-label">Explore '+LOCA.escape(current.label||current.id)+':</span><button type="button" class="sub-chip '+(LOCA.filter===activeMain?'active':'')+'" data-category="'+LOCA.escape(activeMain)+'" onclick="setFilter(this.dataset.category,this)">All '+LOCA.escape(current.label||current.id)+'</button>'+current.subcategories.map(sub=>`<button type="button" class="sub-chip ${LOCA.filter===sub.id?'active':''}" data-category="${LOCA.escape(sub.id)}" onclick="setFilter(this.dataset.category,this)">${LOCA.escape(sub.label)}</button>`).join('')+'</div>'}filters.innerHTML=html}const newGrid=document.getElementById('newGrid');if(newGrid)newGrid.innerHTML=LOCA.products.filter(p=>p.new).slice(0,4).map(LOCA.productCard).join('')||'<p class="catalog-empty">New arrivals are on their way. Explore the collection below.</p>';render();reveal()}
function setFilter(x){LOCA.filter=x;initStoreUI()}
function setFilterFromLink(x){setTimeout(()=>{LOCA.filter=x;initStoreUI();document.getElementById('shop')?.scrollIntoView({behavior:'smooth'})},50)}
function searchProducts(){document.getElementById('shop')?.scrollIntoView({behavior:'smooth'});document.getElementById('productSearch')?.focus({preventScroll:true})}
window.loadProducts=loadProducts;window.render=render;window.setFilter=setFilter;window.setFilterFromLink=setFilterFromLink;window.searchProducts=searchProducts;