window.LOCA=window.LOCA||{};
function ensureSiteNotice(){let layer=document.getElementById('siteNotice');if(layer)return layer;layer=document.createElement('div');layer.id='siteNotice';layer.className='site-notice-layer';layer.setAttribute('role','dialog');layer.setAttribute('aria-modal','true');layer.setAttribute('aria-labelledby','siteNoticeTitle');layer.innerHTML='<div class="site-notice-window"><button class="site-notice-close" type="button" aria-label="Close message">×</button><div class="site-notice-mark" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></svg></div><p class="site-notice-eyebrow"></p><h2 id="siteNoticeTitle"></h2><p class="site-notice-copy"></p><button class="site-notice-action" type="button"></button></div>';const close=()=>closeNotice();layer.querySelector('.site-notice-close').addEventListener('click',close);layer.querySelector('.site-notice-action').addEventListener('click',close);layer.addEventListener('click',event=>{if(event.target===layer)close()});document.body.appendChild(layer);return layer}
function showNotice(options){const config=typeof options==='string'?{title:options}:options||{},layer=ensureSiteNotice();layer.className='site-notice-layer '+(config.tone==='error'?'is-error':config.tone==='success'?'is-success':'is-info');layer.querySelector('.site-notice-eyebrow').textContent=config.eyebrow||'LOCA Collection';layer.querySelector('#siteNoticeTitle').textContent=config.title||'A quick note.';layer.querySelector('.site-notice-copy').textContent=config.message||'';layer.querySelector('.site-notice-action').textContent=config.action||'Continue';layer.classList.add('open');document.body.classList.add('lock');setTimeout(()=>layer.querySelector('.site-notice-action')?.focus(),80)}
function closeNotice(){const layer=document.getElementById('siteNotice');if(!layer)return;layer.classList.remove('open');if(!document.querySelector('.modal-layer.open,.checkout-modal.open,.bag-drawer.open,.site-notice-layer.open'))document.body.classList.remove('lock')}
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&document.getElementById('siteNotice')?.classList.contains('open'))closeNotice()});
LOCA.notice=showNotice;
function toggleMenu(){const nav=document.getElementById('mainNav');const button=document.querySelector('.menu-toggle');const open=nav?.classList.toggle('is-open');button?.setAttribute('aria-expanded',String(!!open));document.body.classList.toggle('menu-open',!!open)}
document.querySelectorAll('#mainNav a').forEach(link=>link.addEventListener('click',()=>{document.getElementById('mainNav')?.classList.remove('is-open');document.querySelector('.menu-toggle')?.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open')}));
function subscribe(event){event.preventDefault();const form=event.currentTarget,msg=document.getElementById('msg');if(msg){msg.textContent="You're on the LOCA list. Watch for the next drop.";msg.className='success-message';msg.style.marginTop='16px'}form?.reset()}
function reveal(){document.querySelectorAll('.reveal').forEach(el=>{if(el.dataset.revealed)return;const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');entry.target.dataset.revealed='1';observer.disconnect()}}),{threshold:.12});observer.observe(el)})}
function ensureSyncPill(){return document.getElementById('syncPill')||null}
async function checkSupabaseConnection(){const pill=ensureSyncPill();if(!pill||!window.LOCA?.db)return;try{pill.classList.remove('error');pill.classList.add('loading');pill.lastElementChild.textContent='Connecting';const{error}=await LOCA.db.from('products').select('id').eq('active',true).limit(1);if(error)throw error;pill.classList.remove('loading');pill.classList.add('ready');pill.lastElementChild.textContent='Catalogue live'}catch(err){console.warn('Catalogue connection check failed',err);pill.classList.remove('loading','ready');pill.classList.add('error');pill.lastElementChild.textContent='Catalogue issue'}}
window.addEventListener('focus',()=>{if(window.LOCA?.currentUser&&window.LOCA?.loadCart)LOCA.loadCart()});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&window.LOCA?.currentUser&&window.LOCA?.loadCart)LOCA.loadCart()});
window.toggleMenu=toggleMenu;window.subscribe=subscribe;window.reveal=reveal;window.checkSupabaseConnection=checkSupabaseConnection;
window.closeNotice=closeNotice;window.showNotice=showNotice;
