(()=>{const db=window.LOCA?.db;const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let rows=[];

function relatedOrders(user){const email=String(user.email||'').trim().toLowerCase();return (orders||[]).filter(order=>{const record=(customers||[]).find(c=>String(c.id)===String(order.customer_id))||{};const orderEmail=String(record.email||order.email||'').trim().toLowerCase();return String(order.user_id||'')===String(user.id)||Boolean(email&&orderEmail===email)}).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));}
function orderItemCount(orderId){return (orderItems||[]).filter(item=>String(item.order_id)===String(orderId)).reduce((sum,item)=>sum+Number(item.quantity||item.qty||0),0);}

async function loadUsers(){const box=$('usersBody'),msg=$('usersMessage');if(!box)return;box.innerHTML='<tr><td colspan="6" class="empty">Loading registered users...</td></tr>';try{const{data,error}=await db.from('profiles').select('*').eq('role','customer').order('created_at',{ascending:false});if(error)throw error;rows=data||[];renderUsers();if(msg)msg.textContent=`${rows.length} registered customer account${rows.length===1?'':'s'} · securely managed through Supabase Auth`;if($('sideUserCount'))$('sideUserCount').textContent=rows.length}catch(error){box.innerHTML=`<tr><td colspan="6" class="empty">${esc(error.message||'Could not load registered users.')}</td></tr>`;adminNotify(error.message||'Could not load registered users.',{title:'Accounts unavailable',tone:'error'})}}

function renderUsers(){const q=($('usersSearch')?.value||'').trim().toLowerCase();const list=rows.filter(user=>`${user.full_name||''} ${user.email||''} ${user.phone||''} ${user.city||''}`.toLowerCase().includes(q));$('usersBody').innerHTML=list.length?list.map(user=>{const count=relatedOrders(user).length;return `<tr><td><b>${esc(user.full_name||'Unnamed customer')}</b><br><span class="muted">${count} order${count===1?'':'s'}</span></td><td>${esc(user.email||'')}</td><td>${esc(user.phone||'Not provided')}</td><td>${esc(user.city||'Not provided')}</td><td>${user.created_at?new Date(user.created_at).toLocaleDateString('en-PK'):'-'}</td><td><div class="user-actions"><button class="smallbtn" type="button" data-user-orders="${esc(user.id)}">View orders</button><button class="smallbtn" type="button" data-user-profile="${esc(user.id)}">Profile</button><button class="smallbtn danger-action" type="button" data-delete-user="${esc(user.id)}">Delete</button></div></td></tr>`}).join(''):'<tr><td colspan="6" class="empty">No registered users match this search.</td></tr>'}

function openUserProfile(id){const user=rows.find(entry=>String(entry.id)===String(id));if(!user)return;renderCustomers();const key=encodeURIComponent(String(user.email||user.id).trim().toLowerCase());openCustomerProfile(key);}

function openUserOrders(id){
  const user=rows.find(entry=>String(entry.id)===String(id));
  if(!user)return;
  const list=relatedOrders(user);
  const spent=list.filter(order=>!['Cancelled','Returned'].includes(order.status)).reduce((sum,order)=>sum+Number(order.total||0),0);
  $('userOrdersTitle').textContent=user.full_name||'Registered customer';
  $('userOrdersEmail').textContent=user.email||'No account email';
  $('userOrderSummary').innerHTML=`<div><span>Orders linked to this account</span><strong>${list.length} order${list.length===1?'':'s'}</strong></div><div><span>Non-cancelled value</span><strong>${money(spent)}</strong></div>`;
  $('userOrdersBody').innerHTML=list.length?list.map(order=>{
    const action=typeof latestCustomerAction==='function'?latestCustomerAction(order.id):null;
    const reason=order.status==='Cancelled'&&order.cancellation_reason?order.cancellation_reason:action?.reason||'';
    const actionNote=action?`<div class="user-order-action-note">Customer · ${esc(action.action_type)}${action.reason?' · '+esc(action.reason):''}</div>`:'';
    return `<article class="user-order-row"><div><strong>${esc(order.order_number||order.order_no||order.id)}</strong><small>${new Date(order.created_at).toLocaleString('en-PK')}</small></div><div><div class="workflow-badges">${orderStatusBadge(order.status)}${paymentStatusBadge(order.payment_status)}</div><small>${orderItemCount(order.id)} item${orderItemCount(order.id)===1?'':'s'} · ${esc(order.payment_method||'COD')}${reason?' · '+esc(reason):''}</small>${actionNote}</div><div class="order-value">${money(order.total)}</div><div class="row-actions"><button class="smallbtn workflow-button" type="button" data-manage-order="${esc(order.id)}">Manage</button><button class="smallbtn" type="button" data-inspect-order="${esc(order.id)}">Inspect</button><button class="smallbtn danger-action" type="button" data-archive-order="${esc(order.id)}">Archive</button></div></article>`;
  }).join(''):'<div class="user-orders-empty">This registered user has not placed an order yet.</div>';
  $('userOrdersModal').dataset.userId=String(user.id);
  $('userOrdersModal').classList.add('open');
  $('userOrdersModal').setAttribute('aria-hidden','false');
}
function closeUserOrders(){$('userOrdersModal')?.classList.remove('open');$('userOrdersModal')?.setAttribute('aria-hidden','true');}

async function functionError(error){try{const body=await error?.context?.json();return body?.error||body?.message||error.message}catch{return error?.message||'The secure delete request failed.'}}
async function getAdminAccessToken(){const{data,error}=await db.auth.getSession();if(error)throw error;let session=data.session;if(!session?.access_token)throw new Error('Your admin session is no longer available. Sign in again.');const expiresAt=Number(session.expires_at||0)*1000;if(expiresAt&&expiresAt-Date.now()<60000){const refreshed=await db.auth.refreshSession();if(refreshed.error)throw refreshed.error;session=refreshed.data.session}if(!session?.access_token)throw new Error('Your admin session has expired. Sign in again.');return session.access_token}
async function deleteUser(id,button){const user=rows.find(entry=>String(entry.id)===String(id));if(!user)return;const label=user.full_name||user.email||'this user';const accepted=await confirmAction({eyebrow:'Permanent account action',title:`Delete ${label}?`,message:`This removes the registered login, profile and saved bag. Existing order records are preserved for store history. This action cannot be undone.`,confirmLabel:'Delete user'});if(!accepted)return;button.disabled=true;button.textContent='Deleting…';try{const accessToken=await getAdminAccessToken();const{data,error}=await db.functions.invoke('admin-delete-user',{body:{user_id:user.id},headers:{Authorization:`Bearer ${accessToken}`}});if(error)throw new Error(await functionError(error));if(data?.error)throw new Error(data.error);if(!data?.success)throw new Error('The user deletion was not confirmed by the server.');closeUserOrders();await db.rpc('resequence_admin_identifiers');await load();await loadUsers();adminNotify(`${label} was deleted. Historical orders remain in the customer book.`,{title:'Registered user removed'})}catch(error){button.disabled=false;button.textContent='Delete';adminNotify(error.message||'The user could not be deleted.',{title:'Delete failed',tone:'error',duration:6000})}}

$('usersSearch')?.addEventListener('input',renderUsers);
$('usersBody')?.addEventListener('click',event=>{const orderButton=event.target.closest('[data-user-orders]');if(orderButton)return openUserOrders(orderButton.dataset.userOrders);const profileButton=event.target.closest('[data-user-profile]');if(profileButton)return openUserProfile(profileButton.dataset.userProfile);const deleteButton=event.target.closest('[data-delete-user]');if(deleteButton)return deleteUser(deleteButton.dataset.deleteUser,deleteButton)});
$('userOrdersBody')?.addEventListener('click',event=>{const manage=event.target.closest('[data-manage-order]');if(manage){closeUserOrders();return openOrderWorkflow(manage.dataset.manageOrder)}const archive=event.target.closest('[data-archive-order]');if(archive){closeUserOrders();return openArchiveOrder(archive.dataset.archiveOrder)}const button=event.target.closest('[data-inspect-order]');if(!button)return;closeUserOrders();viewOrder(button.dataset.inspectOrder)});
$('closeUserOrders')?.addEventListener('click',closeUserOrders);
$('userOrdersModal')?.addEventListener('click',event=>{if(event.target.id==='userOrdersModal')closeUserOrders()});
document.querySelector('.tab[data-tab="users"]')?.addEventListener('click',loadUsers);
window.loadRegisteredUsers=loadUsers;window.openUserOrders=openUserOrders;window.closeUserOrders=closeUserOrders;})();
